### A CI workflow template that runs linting and python testing

name: Test tap-universal-file

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TAP_UNIVERSAL_FILE_FILEPATH: ${{ vars.TAP_UNIVERSAL_FILE_FILEPATH }}
      TAP_UNIVERSAL_FILE_FILE_REGEX: ${{ vars.TAP_UNIVERSAL_FILE_FILE_REGEX }}
      TAP_UNIVERSAL_FILE_PROTOCOL: ${{ vars.TAP_UNIVERSAL_FILE_PROTOCOL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install --extras=s3
    - name: Touch files
      run: |
        touch -t 01021200 /home/runner/work/tap-file/tap-file/tests/data/old_hardware.csv
        touch -t 01031200 /home/runner/work/tap-file/tap-file/tests/data/new_hardware.csv
    - name: Test with pytest
      run: |
        poetry run pytest
